name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: |
          cd example
          flutter config --enable-web
          flutter pub get
          flutter build web --release
          cd build/web
          git init
          # 改成你的提交邮箱
          git config --global user.email jinux111@163.com
          # 改成你的提交用户名
          git config --global user.name jinux
          git status
          # 更改此远程URL，例如查看您的远程URL是 https://github.com/onatcipli/flutter_web.git 然后改成以下内容
          echo "secret:${{secrets.commit_secret}}"
          git remote add origin https://${{secrets.commit_secret}}@github.com/jinguoliang/flutter_image_crop_widget-.git
          git checkout -b gh-pages
          echo 'checout -b gh-pages'
          git add --all
          git commit -m "update"
          echo 'commited'
          git push origin gh-pages -f
